In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [12]:
import sys
import time
l = range(1000)
print(sys.getsizeof(5)*len(l))



28000


In [13]:
arr = np.arange(1000)
print(arr.size*arr.itemsize)

4000


In [27]:
size = 10000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print(f"python list took {(time.time()-start)*1000}")

python list took 2438.8270378112793


In [28]:
start = time.time()
result = a1 + a2
print(f"numpy took {(time.time()-start)*1000}")

numpy took 227.29921340942383


In [29]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [35]:
a1 % a2

array([1, 2, 3, 4])

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
a.ndim

2

In [38]:
a.itemsize

4

In [39]:
a.dtype

dtype('int32')

In [40]:
b = np.array(a,dtype=np.float64)

In [41]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [42]:
b.dtype

dtype('float64')

In [43]:
b.size

9

In [44]:
b.itemsize

8

In [45]:
a.shape

(3, 3)

In [46]:
c = np.array(a,dtype=np.complex_)

In [47]:
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [48]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.arange(1,9).reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [59]:
np.arange(1,9).reshape((4,2)).ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a.min()

1

In [62]:
a.max()

9

In [63]:
a.sum()

45

In [65]:
a.max(axis=0)

array([7, 8, 9])

In [66]:
a.max(axis=1)

array([3, 6, 9])

In [67]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
np.std(a)

2.581988897471611

In [71]:
a = np.array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
b = np.array([
       [7, 8, 9],
       [10,11,12],
       [1,2,3]
       ])

In [76]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 84,  99, 114]])

In [77]:
a@b

array([[ 30,  36,  42],
       [ 84,  99, 114]])

In [78]:
a@b.T

array([[ 50,  68,  14],
       [122, 167,  32]])

In [79]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
a[1:2]

array([[4, 5, 6]])

In [81]:
a[:,1]

array([2, 5])

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
for x in a:
    for i in x:
        print(i)
   

1
2
3
4
5
6


In [85]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6


In [88]:

for i in a.ravel():
    print(i)

1
2
3
4
5
6


In [96]:
a = np.arange(6).reshape((3,2))
b = np.arange(6,12).reshape(3,2)

In [97]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [98]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [99]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [100]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [101]:
np.hsplit(a,2)

[array([[0],
        [2],
        [4]]),
 array([[1],
        [3],
        [5]])]

In [106]:
np.vsplit(a,3)

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]

In [105]:
type(np.vsplit(a,3))

list

In [107]:
a = np.arange(12).reshape(3,4)

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a > 7

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [110]:
b = a>5

In [116]:
a*b

array([[ 0,  0,  0,  0],
       [ 0,  0,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

In [118]:
a[b] = -1

In [119]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [120]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [121]:
a = np.arange(12).reshape(3,4)

In [122]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [130]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [131]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [133]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [134]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
for i in 